apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: daryl-test
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      k8s-app: redis
  template:
    metadata:
      labels:
        k8s-app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0.0
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-conf
          mountPath: /usr/local/etc/redis/
        - name: redis-data
          mountPath: /data
        command:
          - "redis-server"
          - "/usr/local/etc/redis/redis.conf"
    volumes:
      - configMap:
          name: redis-conf
        name: redis-conf
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "daryl-balabalabala"
        resources:
          requests:
            storage: 1Gi