apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: daryl-test
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    k8s-app: redis
  type: ClusterIP