- name: create a floder for nginx.conf
  shell: "mkdir -p /opt/nginx"

- name: copy nginx.conf
  template: src=nginx.conf.j2 dest=/opt/nginx/nginx.conf

- name: run a nginx web server
  docker_container:
    name: web-server
    image: nginx:1.21
    state: started
    links:
      - "api-server:api-server"
    volumes:
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"